lcm:Fix ld error.
16:16:14  pcre2/src/pcre2_compile.c:2653:18: note: each undeclared identifier is reported only once for each function it appears in
16:16:14  pcre2/src/pcre2_compile.c:2660:18: error: 'PCRE2_EXTRA_ASCII_BSS' undeclared (first use in this function); did you mean 'PCRE2_EXTRA_ALT_BSUX'?
16:16:14   2660 |   ascii_option = PCRE2_EXTRA_ASCII_BSS;
16:16:14        |                  ^~~~~~~~~~~~~~~~~~~~~

PCRE2_EXTRA_ASCII_BSS is defined in ./external/pcre2/pcre2/pcre2.h

Signed-off-by: cuiziwei <cuiziwei@xiaomi.com>